name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # Organization name, e.g., 'aiadaptiv'
          password: ${{ secrets.GITHUB_TOKEN }} # Scoped to the organization

      - name: Build and push Docker image
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_OWNER/aihelpers:latest .
          docker push ghcr.io/$REPO_OWNER/aihelpers:latest

      - name: Deploy to Droplet
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          echo "$DEPLOY_KEY" > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key kacper@$DROPLET_IP << 'EOF'
            cd ~/my-node-app
            docker-compose pull
            docker-compose up -d
          EOF
          rm deploy_key
