name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/kacper-hernacki/aihelpers:latest .
          docker push ghcr.io/kacper-hernacki/aihelpers:latest

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: kacper
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/aiAdaptiv

            # Stop and remove any existing containers
            docker-compose down || true
            docker stop aihelpers-app || true
            docker rm aihelpers-app || true

            # Pull the latest image
            docker pull ghcr.io/kacper-hernacki/aihelpers:latest

            # Run the container directly with Docker instead of Docker Compose
            docker run -d \
              --name aihelpers-app \
              -p 3000:3000 \
              -e NODE_ENV=production \
              -e API_KEY=${{ secrets.API_KEY }} \
              --restart unless-stopped \
              ghcr.io/kacper-hernacki/aihelpers:latest
