name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files for debugging
        run: ls -R

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/kacper-hernacki/aihelpers:latest \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} .
          docker push ghcr.io/kacper-hernacki/aihelpers:latest

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: kacper
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/aiAdaptiv

            # Stop and remove any existing containers
            docker-compose down || true
            docker stop aihelpers-app || true
            docker rm aihelpers-app || true

            # Pull the latest image
            docker pull ghcr.io/kacper-hernacki/aihelpers:latest

            # Run the container directly with Docker
            docker run -d \
              --name aihelpers-app \
              -p 3000:3000 \
              -e NODE_ENV=production \
              -e API_KEY=${{ secrets.API_KEY }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e COMFYICU_API_KEY=${{ secrets.COMFYICU_API_KEY }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e DO_SPACES_ENDPOINT=${{ secrets.DO_SPACES_ENDPOINT }} \
              -e DO_SPACES_REGION=${{ secrets.DO_SPACES_REGION }} \
              -e DO_SPACES_ACCESS_KEY=${{ secrets.DO_SPACES_ACCESS_KEY }} \
              -e DO_SPACES_SECRET_KEY=${{ secrets.DO_SPACES_SECRET_KEY }} \
              -e DO_SPACES_BUCKET=${{ secrets.DO_SPACES_BUCKET }} \
              --restart unless-stopped \
              ghcr.io/kacper-hernacki/aihelpers:latest

            # Use systemctl without sudo if configured properly
            systemctl is-active nginx && systemctl restart nginx || echo "Nginx not running or restart failed"
